### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'touched' of undefined

### ISSUE THREAD

**Issue by joma74** [marmelab/admin-on-rest-demo#12]
First off let me say that i feel you produced, made public and described a substantial piece of frontend architecture. 

Unluckily, stepping through the demo, it grinded to a halt. Console output is

```js
Using '^' to denote the start of a url is deprecated. Use 'begin:' instead
GET http://localhost:3000/commands?sort=%5B%22date%22%2C%22DESC%22%5D&range=%5B0%2C49%5D&filter=%7B%22date_gte%22%3A%222017-03-12T08%3A46%3A12.345Z%22%7D (FakeRest)
GET http://localhost:3000/reviews?sort=%5B%22date%22%2C%22DESC%22%5D&range=%5B0%2C99%5D&filter=%7B%22status%22%3A%22pending%22%7D (FakeRest)
GET http://localhost:3000/customers?sort=%5B%22first_seen%22%2C%22DESC%22%5D&ra…d%22%3Atrue%2C%22first_seen_gte%22%3A%222017-03-12T08%3A46%3A12.345Z%22%7D (FakeRest)
GET http://localhost:3000/customers?filter=%7B%22id%22%3A%5B880%2C880%2C880%2C298%2C844%2C844%2C844%2C898%2C195%2C20%2C195%2C441%2C334%2C441%2C866%5D%7D (FakeRest)
GET http://localhost:3000/customers?filter=%7B%22id%22%3A%5B446%2C844%2C11%2C195%2C386%2C860%2C745%2C773%2C195%2C195%5D%7D (FakeRest)
GET http://localhost:3000/commands/272 (FakeRest)
GET http://localhost:3000/products?filter=%7B%22id%22%3A%5B17%2C89%2C20%2C112%2C47%5D%7D (FakeRest)
GET http://localhost:3000/customers/195 (FakeRest)
GET http://localhost:3000/customers?sort=%5B%22id%22%2C%22DESC%22%5D&range=%5B0%2C24%5D&filter=%7B%7D (FakeRest)
GET http://localhost:3000/commands?sort=%5B%22date%22%2C%22DESC%22%5D&range=%5B0%2C24%5D&filter=%7B%7D (FakeRest)
GET http://localhost:3000/customers?filter=%7B%22id%22%3A%5B%2220%22%2C%22195%2…22521%22%2C%22835%22%2C%22844%22%2C%22866%22%2C%22880%22%2C%22898%22%5D%7D (FakeRest)
GET http://localhost:3000/customers?sort=%5B%22last_seen%22%2C%22DESC%22%5D&range=%5B0%2C24%5D&filter=%7B%7D (FakeRest)
GET http://localhost:3000/commands?sort=%5B%22date%22%2C%22DESC%22%5D&range=%5B0%2C49%5D&filter=%7B%22date_gte%22%3A%222017-03-12T08%3A46%3A42.320Z%22%7D (FakeRest)
GET http://localhost:3000/reviews?sort=%5B%22date%22%2C%22DESC%22%5D&range=%5B0%2C99%5D&filter=%7B%22status%22%3A%22pending%22%7D (FakeRest)
GET http://localhost:3000/customers?sort=%5B%22first_seen%22%2C%22DESC%22%5D&ra…d%22%3Atrue%2C%22first_seen_gte%22%3A%222017-03-12T08%3A46%3A42.320Z%22%7D (FakeRest)
GET http://localhost:3000/customers?filter=%7B%22id%22%3A%5B880%2C880%2C880%2C298%2C844%2C844%2C844%2C898%2C195%2C20%2C195%2C441%2C334%2C441%2C866%5D%7D (FakeRest)
GET http://localhost:3000/customers?filter=%7B%22id%22%3A%5B446%2C844%2C11%2C195%2C386%2C860%2C745%2C773%2C195%2C195%5D%7D (FakeRest)
Uncaught (in promise) TypeError: Cannot read property 'touched' of undefined
    at t.value (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:8:6741)
    at _renderValidatedComponentWithoutOwnerOrContext (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:6950)
    at _renderValidatedComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:7077)
    at performInitialMount (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:2896)
    at mountComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:1942)
    at Object.mountComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:4:3216)
    at performInitialMount (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:3056)
    at mountComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:1942)
    at Object.mountComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:4:3216)
    at performInitialMount (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:3056)
    at mountComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:1942)
GET http://localhost:3000/commands?sort=%5B%22id%22%2C%22DESC%22%5D&range=%5B0%2C24%5D&filter=%7B%22customer_id%22%3A844%7D (FakeRest)
GET http://localhost:3000/reviews?sort=%5B%22id%22%2C%22DESC%22%5D&range=%5B0%2C24%5D&filter=%7B%22customer_id%22%3A844%7D (FakeRest)
uncaught at t TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:4:3368)
    at getHostNode (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:3153)
    at Object.getHostNode (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:4:3369)
    at Object.updateChildren (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:37:31513)
    at h._reconcilerUpdateChildren (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:39:353)
    at h._updateChildren (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:39:1118)
    at h.updateChildren (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:39:1016)
    at h._updateDOMChildren (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:17873)
    at h.updateComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:16097)
    at h.receiveComponent (https://marmelab.com/admin-on-rest-demo/static/js/main.300a19f9.js:38:15650)
Uncaught TypeError: Cannot read property 'getHostNode' of null
Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null(…)
Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null(…)
```

**Comment by fzaninotto** [comment]
I believe this is solved in the `next` branch.

**Comment by fzaninotto** [comment]
No news for some time, closing.
