### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by spsenthil** [marmelab/admin-on-rest-demo#24]
npm start 
----------

> admin-on-rest-demo@1.2.0 start /Users/dcteam/Documents/GitRepo/sp-react/admin-on-rest-demo
> react-scripts start

/Users/dcteam/Documents/GitRepo/sp-react/admin-on-rest-demo/node_modules/react-scripts/scripts/start.js:31
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

**Comment by fzaninotto** [comment]
You need a more recent version of Node.js
